config/routes.rb
Rails.application.routes.draw do
 
  #Rota Money Finalizadas 
  get 'moneys_exe/index'
  post 'moneys_exe/index'
  get '/export' => 'moneys_exe#export'
  
  #Historico de Justificativas
  
  get 'points_exe/index'
  post 'points_exe/index'
  

  #ROTA HISTORICO SALARIAL 
  get 'hist_moneys/index'
  post 'hist_moneys/index'

  #ROTA PONTO
  get 'points/index'
  post 'points/index'
  post 'points/justificar' => 'points#justificar'
  #post 'points/enviarTwo' => 'points#enviarTwo'
  get  'points/salvarDados'

  #Rota Money
  get 'moneys/index'
  post 'moneys/index'
  get '/money_export' => 'moneys#export'
  
  #exportando_pfd
  #get 'moneys/export'
   
  #Rota Dados Funcionários
  get 'dice/index'

  #Rota Página Principal
  get 'pages/index'
  delete 'pages/destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #Rotas login
  get 'login/index'
  root 'login#index'

end

app/controllers/moneys_controller.rb
class MoneysController < ApplicationController
  layout 'site'
  require 'pdfkit'

   def index 
    
      if params[:commit].to_s == "Enviar"
      #puts "enviando valores"
       enviarDados(params[:ano],params[:mes]) 
        request[:ano] = params[:ano]
        request[:mes] = params[:mes]
      else
       puts "ERROU!" 
      end
   
   end 
  
  def enviarDados(ano,mes)
   
    client = Savon.client(
    :wsdl => 'http://10.1.11.161/TOTVSBusinessConnect/wsConsultaSQL.asmx?wsdl',
    :log => true,
    :pretty_print_xml => true,
    basic_auth:["4456","040113"],
    ssl_verify_mode: :none,
    log_level: :debug, 
  )
  message = {
    #"codSentenca" => 'BATIDASS',
    #"codColigada" => '0',
    #"codAplicacao" => 'Y',
    #"Usuario" =>'mestre',
    #"Senha" => '@Pintos2019',
    #"parameters" => 'COD_PESSOA=4062;DATA_INI=2019-03-01 00:00:00;DATA_FIM=2019-03-10 00:00:00;',
    
    "codSentenca" => 'NEWPORTAL01_02',
    "codColigada" => '1',
    "codAplicacao" => 'P',
    "Usuario" => session[:username],
    "Senha" => session[:password],
    'parameters' => "'COD_PESSOA="+session[:username]+";ANO_COMP="+request[:ano]+";MES_COMP="+request[:mes]+";PEVENTO.CODIGO IN('N001');'",
}

response = client.call(
      :realizar_consulta_sql_auth,
      message: message,
  )
  
  result = response.body[:realizar_consulta_sql_auth_response][:realizar_consulta_sql_auth_result]
  
  doc = Nokogiri::Slop(result)
  
  @result = doc.NewDataSet.Resultado

  rescue Exception => e 
   
  e.message

  end

  def show
  
  @result = doc.NewDataSet.Resultado

  end

  def export 
      
      #html = render_to_string(:action => "show", :layout => false)
      #kit = PDFKit.new(html)
      #kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/pdf.css"
      #kit.to_file("#{Rails.root}/public/system/daoe/daoe" + @daoe.id.to_s+'.pdf')
      #send_data(kit.to_pdf, :filename => 'report.pdf', :type => 'application/pdf', :disposition => 'inline')  
  end 

 
end

app/helpers/moneys_helper.rb
module MoneysHelper
end

app/views/moneys/index.html.erb
<div class="container_moneys">

<div class="mover_two">  
<form> 
 <h2> Demonstrativos de Pagamentos </h2>
 <br/>
  <div class="form-row">
  <%= form_tag moneys_index_path do %>
    <div class="form-group col-md-3">
      <label>Informe o Ano da Competência</label>
      <%= text_field_tag :ano , "", class: 'form-control' %>
    </div>
    <div class="form-group col-md-3">
      <label>Informe o Mês da Competência </label>
      <%= text_field_tag :mes , "", class: 'form-control'%> 
    </div>
  </div>
   <div class="form-group col-md-3">
      <%= submit_tag "Enviar" , class: 'btn btn-primary'%>
    </div>
  </div>
  <% end %>
</form>
   

  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">NOME</th>
      <th scope="col">DESCRIÇÃO</th>
      <th scope="col">COMPETÊNCIA</th>
      <th scope="col">NROPERIODO</th>
      <th scope="col">DTPAGTO</th>
      <th scope="col">DESCRIÇÃO</th>
      <th scope="col">LIQUIDO</th>
      <th scope="col">SALARIO</th>
    </tr>
  </thead>
  <tbody>
     
    <tr>
      <td><%= @result.try(:NOME).try(:content)%></td>
      <td><%= @result.try(:DESCRICAO1).try(:content) %></td>
      <td><%= @result.try(:MESCOMP).try(:content)%></td>
      <td><%= @result.try(:NROPERIODO).try(:content) %></td>
      <td><%= @result.try(:DTPAGTO).try(:content) %></td>
      <td><%= @result.try(:DESCRICAO).try(:content) %></td>
      <td><%= @result.try(:SALARIOPAGO).try(:content) %></td>
      <td><%= @result.try(:SALARIO).try(:content) %></td>
      <td> 
      <%= link_to 'Gerar PDF', money_export_path, class: 'btn btn-success'%>
       </td>
      
    </tr>
     
  </tbody>
   
</table>


</div> 

</div>

app/views/moneys/show.html.erb
<div class="container" style="width: 700px;height: 0 auto;border: 1px solid grey;margin: 50px; padding: 50px;">

<h2 class="text-center"> Demonstrativo de Pagamento Mensal </h2>
<table>
      <td><%= @result.try(:NOME).try(:content)%> &lt;ENDERECO_LOJA&gt;Rua Alvaro Mendes, 1237 - Centro - Teresina/ PI&lt;/ENDERECO_LOJA&gt; </td>
      <td><%= @result.try(:DESCRICAO1).try(:content) %></td>
      <td><%= @result.try(:MESCOMP).try(:content)%></td>
      <td><%= @result.try(:NROPERIODO).try(:content) %></td>
      <td><%= @result.try(:CODEVENTO).try(:content) %></td>
      <td><%= @result.try(:DTPAGTO).try(:content) %></td>
      <td><%= @result.try(:VALOR).try(:content)%></td>
      <td><%= @result.try(:DESCRICAO).try(:content) %></td>
      <td><%= @result.try(:SALARIOPAGO).try(:content) %></td>
      <td><%= @result.try(:SALARIO).try(:content) %></td> 

       <td> TESTE </td>
</table>    


</div>  


  
<!-- 
    &lt;CARTEIRATRAB&gt;9429394&lt;/CARTEIRATRAB&gt;
    &lt;SERIECARTTRAB&gt;0040&lt;/SERIECARTTRAB&gt;
    &lt;CODIGO&gt;1.001.04.05.01&lt;/CODIGO&gt;
    &lt;LOJA&gt;1.001&lt;/LOJA&gt;
    &lt;ENDERECO_LOJA&gt;Rua Alvaro Mendes, 1237 - Centro - Teresina/ PI&lt;/ENDERECO_LOJA&gt;
    &lt;ENDERECO_PESSOA&gt;Quadra 12 Casa 23 Setor A, 23Mocambinho, Teresina/ PI&lt;/ENDERECO_PESSOA&gt;
    &lt;CEP_PESSOA&gt;64010040&lt;/CEP_PESSOA&gt;
    &lt;COMPLEMENTO_PESSOA /&gt;
    &lt;CODFUNCAO&gt;F074&lt;/CODFUNCAO&gt;
    &lt;DTMUDANCA&gt;2018-12-05T00:00:00-03:00&lt;/DTMUDANCA&gt;
    &lt;CODBANCOPGTO&gt;001&lt;/CODBANCOPGTO&gt;
    &lt;CODAGENCIAPGTO&gt;3506&lt;/CODAGENCIAPGTO&gt;
    &lt;CONTAPGTO&gt;36505X&lt;/CONTAPGTO&gt;
    &lt;OPBANCARIA /&gt;
    &lt;TPCONTABANCARIA /&gt;
    &lt;PRINCIPAL&gt;S&lt;/PRINCIPAL&gt;
    &lt;NOME2&gt;Banco do Brasil&lt;/NOME2&gt;
    &lt;HORA&gt;31&lt;/HORA&gt;
    &lt;ALTERADOMANUAL&gt;0&lt;/ALTERADOMANUAL&gt;
    &lt;VERBAFERIAS&gt;0&lt;/VERBAFERIAS&gt;
    &lt;ORIGEMMOV&gt;0&lt;/ORIGEMMOV&gt;
    &lt;RECCREATEDBY&gt;Paulo&lt;/RECCREATEDBY&gt;
    &lt;RECCREATEDON&gt;2019-09-04T13:30:08-03:00&lt;/RECCREATEDON&gt;
    &lt;RECMODIFIEDBY&gt;Paulo&lt;/RECMODIFIEDBY&gt;
    &lt;RECMODIFIEDON&gt;2019-09-05T12:38:46-03:00&lt;/RECMODIFIEDON&gt;
    &lt;VERBARESILICAO&gt;0&lt;/VERBARESILICAO&gt;
    &lt;VERBADIFERENCA&gt;0&lt;/VERBADIFERENCA&gt;
    &lt;MESCAIXACOMUM&gt;9&lt;/MESCAIXACOMUM&gt;
    &lt;VALORESFORCADOS&gt;0&lt;/VALORESFORCADOS&gt;
    &lt;MOVIMPORTADO&gt;0&lt;/MOVIMPORTADO&gt;
    &lt;EDITADO&gt;0&lt;/EDITADO&gt;
    &lt;ALTERADO&gt;0&lt;/ALTERADO&gt;
    &lt;SALCOMISSAO&gt;0&lt;/SALCOMISSAO&gt;
    &lt;FERIASMES&gt;0&lt;/FERIASMES&gt;
    &lt;BASEINSS&gt;1407.41&lt;/BASEINSS&gt;
    &lt;BASEINSSOUTROEMP&gt;0&lt;/BASEINSSOUTROEMP&gt;
    &lt;INSS&gt;112.59&lt;/INSS&gt;
    &lt;INSSFERIAS&gt;0&lt;/INSSFERIAS&gt;
    &lt;INSSOUTROEMP&gt;0&lt;/INSSOUTROEMP&gt;
    &lt;BASEINSS13&gt;0&lt;/BASEINSS13&gt;
    &lt;BASEINSS13OUTRO&gt;0&lt;/BASEINSS13OUTRO&gt;
    &lt;INSS13&gt;0&lt;/INSS13&gt;
    &lt;BASESALFAMILIA&gt;1436.30&lt;/BASESALFAMILIA&gt;
    &lt;SALFAMILIA&gt;0&lt;/SALFAMILIA&gt;
    &lt;BASEVALETRANSP&gt;1406.36&lt;/BASEVALETRANSP&gt;
    &lt;VALETRANSPENTR&gt;0&lt;/VALETRANSPENTR&gt;
    &lt;VALETRANSPDESC&gt;0&lt;/VALETRANSPDESC&gt;
    &lt;BASEIRRF&gt;1407.41&lt;/BASEIRRF&gt;
    &lt;IRRF&gt;0&lt;/IRRF&gt;
    &lt;INSSCAIXA&gt;112.59&lt;/INSSCAIXA&gt;
    &lt;DEDUTIVELIRRF&gt;0&lt;/DEDUTIVELIRRF&gt;
    &lt;BASEIRRFPART&gt;0&lt;/BASEIRRFPART&gt;
    &lt;IRRFPART&gt;0&lt;/IRRFPART&gt;
    &lt;BASEIRRFFERIAS&gt;0&lt;/BASEIRRFFERIAS&gt;
    &lt;IRRFFERIAS&gt;0&lt;/IRRFFERIAS&gt;
    &lt;INSSCOMCPMF&gt;112.59&lt;/INSSCOMCPMF&gt;
    &lt;DESCRICAO&gt;Folha Mensal&lt;/DESCRICAO&gt;
    &lt;BASEFGTS&gt;1407.41&lt;/BASEFGTS&gt;
    &lt;BASEFGTS13&gt;0&lt;/BASEFGTS13&gt;
    &lt;STATUSCCUSTO&gt;1&lt;/STATUSCCUSTO&gt;
    &lt;BASEIRRF13&gt;0&lt;/BASEIRRF13&gt;
    &lt;SALARIODECALCULO&gt;1406.36&lt;/SALARIODECALCULO&gt;
    &lt;IRRF13&gt;0&lt;/IRRF13&gt;
    &lt;INSSFERIASCOMCPMF&gt;0&lt;/INSSFERIASCOMCPMF&gt;
    &lt;INSSCALCUSUARIO&gt;0&lt;/INSSCALCUSUARIO&gt;
    &lt;BASEFGTSDIFSAL&gt;0&lt;/BASEFGTSDIFSAL&gt;
    &lt;INSSDIFSAL&gt;0&lt;/INSSDIFSAL&gt;
    &lt;INSSDIFSAL13&gt;0&lt;/INSSDIFSAL13&gt;
    &lt;INSSDIFSALFER&gt;0&lt;/INSSDIFSALFER&gt;
    &lt;EXECID&gt;8cc1f526-9eab-4525-a9c4-fc1ef58db23c&lt;/EXECID&gt;
    &lt;RECCREATEDBY1&gt;Paulo&lt;/RECCREATEDBY1&gt;
    &lt;RECCREATEDON1&gt;2019-08-13T14:45:52-03:00&lt;/RECCREATEDON1&gt;
    &lt;RECMODIFIEDBY1&gt;Paulo&lt;/RECMODIFIEDBY1&gt;
    &lt;RECMODIFIEDON1&gt;2019-09-05T12:38:46-03:00&lt;/RECMODIFIEDON1&gt;
    &lt;NRODEPENDIRRF&gt;0&lt;/NRODEPENDIRRF&gt;
    &lt;LIQUIDO&gt;607.28&lt;/LIQUIDO&gt;
    &lt;NRODEPENDSALFAMILIA&gt;0&lt;/NRODEPENDSALFAMILIA&gt;
    &lt;RETIFICACAO&gt;0&lt;/RETIFICACAO&gt;
    &lt;DTMUDANCA1&gt;2018-12-05T00:00:00-03:00&lt;/DTMUDANCA1&gt;
 
    &lt;CGC&gt;06.837.645/0001-60&lt;/CGC&gt;
    &lt;SALARIO&gt;1406.36&lt;/SALARIO&gt;
   --> 