config/routes.rb
Rails.application.routes.draw do
 
  #Rota Money Finalizadas 
  get 'moneys_exe/index'
  post 'moneys_exe/index'
  get '/export' => 'moneys_exe#export'
  
  #Historico de Justificativas
  
  get 'points_exe/index'
  post 'points_exe/index'
  

  #ROTA HISTORICO SALARIAL 
  get 'hist_moneys/index'
  post 'hist_moneys/index'

  #ROTA PONTO
  get 'points/index'
  post 'points/index'
  post 'points/justificar' => 'points#justificar'
  #post 'points/enviarTwo' => 'points#enviarTwo'
  get  'points/salvarDados'

  #Rota Money
  get 'moneys/index'
  post 'moneys/index'
  get '/money_export' => 'moneys#export'
  
  #exportando_pfd
  #get 'moneys/export'
   
  #Rota Dados Funcionários
  get 'dice/index'

  #Rota Página Principal
  get 'pages/index'
  delete 'pages/destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #Rotas login
  get 'login/index'
  root 'login#index'

end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  layout 'site'

   def index 
    
      if params[:commit].to_s == "Enviar"
      #puts "enviando valores"
       enviarDados(params[:data_ini],params[:data_fim]) 
        request[:data_ini] = params[:data_ini]
        request[:data_fim] = params[:data_fim]
      else
       puts "ERROU!" 
      end
   
   end 
  
  def enviarDados(data_ini,data_fim)
   
    client = Savon.client(
    :wsdl => 'http://10.1.11.161/TOTVSBusinessConnect/wsConsultaSQL.asmx?wsdl',
    :log => true,
    :pretty_print_xml => true,
    basic_auth:["4456","040113"],
    ssl_verify_mode: :none,
    log_level: :debug, 
  )
  message = {
    #"codSentenca" => 'BATIDASS',
    #"codColigada" => '0',
    #"codAplicacao" => 'Y',
    #"Usuario" =>'mestre',
    #"Senha" => '@Pintos2019',
    #"parameters" => 'COD_PESSOA=4062;DATA_INI=2019-03-01 00:00:00;DATA_FIM=2019-03-10 00:00:00;',
    
    "codSentenca" => 'NEWPORTAL01_03',
    "codColigada" => '1',
    "codAplicacao" => 'P',
    "Usuario" => session[:username],
    "Senha" => session[:password],
    'parameters' => "'COD_PESSOA="+session[:username]+";DATA_INI="+request[:data_ini]+";DATA_FIM="+request[:data_fim]+";",
}

response = client.call(
      :realizar_consulta_sql_auth,
      message: message,
  )
  
  result = response.body[:realizar_consulta_sql_auth_response][:realizar_consulta_sql_auth_result]
  
  doc = Nokogiri::Slop(result)
  
  @result = doc.NewDataSet.Resultado
 

  rescue Exception => e 
   
  e.message

  end
 
 def justificar
    
  if params[:commit].to_s == "Enviar"
    #puts "enviando valores"
     salvarDados(params[:chapa],params[:motivo],params[:tipoocorrencia]) 
      request[:chapa] = params[:chapa]
      request[:motivo] = params[:motivo] 
      request[:tipoocorrencia] = params[:tipoocorrencia] 
  else
     redirect_to points_index_path, flash: { error: 'Nao foi possivel enviar os dados, para salvar !'}
  end

 end
 
 def salvarDados(chapa,motivo,tipoocorrencia)
   
  @client = Savon.client(
    :wsdl => 'http://10.1.11.161/TOTVSBusinessConnect/wsDataServer.asmx?wsdl',
    # env_namespace: :soapenv,
    # element_form_default: :qualified,
    :log => true,
    :pretty_print_xml => true,
    basic_auth:["4456","040113"],
    ssl_verify_mode: :none,
    log_level: :debug,
    encoding: 'UTF-8',
    #:content_type => "text/xml;charset=UTF-8", 
  )

  message = {
    'DataServerName' => 'PTODATAJUSTIFICATIVAEXCECOES',
    'XML' => '<![CDATA[
      <NewDataSet>
        <AJUSTFUN>
         <CODCOLIGADA>1</CODCOLIGADA>
         <CHAPA>'+request[:chapa]+'</CHAPA>
         <DATA>2020-01-25T00:00:00</DATA>
         <INICIO>850</INICIO>
         <FIM>1125</FIM>
         <NUMHORASSTR>04:35</NUMHORASSTR>
         <INICIOSTR>14:10</INICIOSTR>
         <FIMSTR>18:45</FIMSTR>
         <TIPOOCORRENCIA>'+request[:tipoocorrencia]+'</TIPOOCORRENCIA>
         <JUSTIFICATIVA>'+request[:motivo]+'</JUSTIFICATIVA>
         <ATITUDE>0</ATITUDE>
         <NUMHORAS>275</NUMHORAS>
         <CAMPOCALCULADO/>
         <ATITUDESTR/>
        </AJUSTFUN>
       </NewDataSet>]]>',
    'Contexto' => 'CODCOLIGADA=1;CODSISTEMA=G;CODUSUARIO=mestre;',
    'Usuario' => '4456',
    'Senha' => '040113',
  }  

  response = @client.call(
    :save_record_auth,
    message: message,
  )

  result = response.body[:save_record_auth_response][:save_record_auth_result]
  
  puts result

  #doc = Nokogiri::Slop(result)
  
  #@result = doc.NewDataSet
 
  rescue Exception => e 
   
  e.message 

 end

end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/index.html.erb
<div class="container_points">

<div class="mover_tree">  
<form> 
 <h2> Espelho de Ponto  </h2>
 <br/>
  <div class="form-row">
  <%= form_tag points_index_path do %>
    <div class="form-group col-md-6">
      <label>Informe uma Data Inicial :</label>
      <%= date_field_tag :data_ini , "", class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <label>Informe uma Data Final : </label>
      <%= date_field_tag :data_fim , "", class: 'form-control'%> 
    </div>
  </div>
   <div class="form-group col-md-6">
      <%= submit_tag "Enviar" , class: 'btn btn-primary'%>
    </div>
  </div>
  <% end %>
</form>
   

  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">BATIDAS</th>
      <th scope="col">HORARIO</th>
      <th scope="col">DATA</th>
      
      <th scope="col">AÇÕES</th>
    </tr>
  </thead>
    <%#= form_tag points_justificar_path do %>
  <tbody>
   
      <% if @result.present? %>
       <% @result.each do |point| %> 
       
    <tr>
      <td><%= point.try(:BATIDAS).try(:content)%></td>
      <td><%= point.try(:HORARIO).try(:content) %></td>
      <td><%= point.try(:DATA).try(:content)%></td>
      <td> 
      <%#= text_field_tag :chapa ,"",class: 'form-control'  %>   
      <td> 
       <!--   <select class="form-control"> 
           <option> FALTA </option>
           <option> ATRASO </option>
           <option> EXTRA </option>
         </select> --> 
      
       <%#= text_field_tag :tipoocorrencia ,"",class: 'form-control'  %> 

      </td>

      <td> 
        <!-- <select class="form-control"> 
           <option> Problemas Particulares - Teste </option>
           <option> Problemas Particulares - Teste EXTRA </option>
           <option> Problemas Particulares - Teste ATRASO </option>
         </select> -->
    
       <%#= text_field_tag :motivo ,"",class: 'form-control'  %> 

      </td>
     <td> 
      <%#= link_to 'Justificar ', points_enviarTwo_path, class: 'btn btn-warning'%> | 
      <%#= submit_tag "Enviar" , class: 'btn btn-primary'%>
       </td>
      
    </tr>

      <%# end %>
     <% end %>
    <% end %>    
  </tbody>
   
</table>


</div> 

</div>