config/routes.rb
Rails.application.routes.draw do
 
  #Rota Money Finalizadas 
  get 'moneys_exe/index'
  post 'moneys_exe/index'
  get '/export' => 'moneys_exe#export'
  
  #Historico de Justificativas
  
  get 'points_exe/index'
  post 'points_exe/index'
  

  #ROTA HISTORICO SALARIAL 
  get 'hist_moneys/index'
  post 'hist_moneys/index'

  #ROTA PONTO
  get 'points/index'
  post 'points/index'
  post 'points/justificar' => 'points#justificar'
  #post 'points/enviarTwo' => 'points#enviarTwo'
  get  'points/salvarDados'

  #Rota Money
  get 'moneys/index'
  post 'moneys/index'
  get '/money_export' => 'moneys#export'
  
  #exportando_pfd
  #get 'moneys/export'
   
  #Rota Dados Funcionários
  get 'dice/index'

  #Rota Página Principal
  get 'pages/index'
  delete 'pages/destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #Rotas login
  get 'login/index'
  root 'login#index'

end

app/views/layouts/site_layout/_config_site.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 

app/views/layouts/site_layout/_site_header.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Pintos Portal</title>
 
    <meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">PINTOS LTDA</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Ajuda ? " aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
       <%= link_to "SAIR", pages_destroy_path(params[:username],params[:password]), method: :delete, data: { confirm: 'Tem Certeza?' }, class: "nav-link" %>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
              <%= link_to 'Página Principal', pages_index_path , class: 'nav-link active'%>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
               <%= link_to 'Meus Dados', dice_index_path , class: 'nav-link'%>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
               <%= link_to 'Demonstrativos de Pagamentos', moneys_exe_index_path , class: 'nav-link'%>
              
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Informe de Rendimentos
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              <%= link_to 'Histórico Salarial', hist_moneys_index_path , class: 'nav-link'%>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Alteração Cadastral
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Ponto</span>
          <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="">
              <span data-feather="file-text"></span>
               <%= link_to 'Histórico Batida', points_index_path , class: 'nav-link'%>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              <%= link_to 'Justificativas', points_exe_index_path , class: 'nav-link'%>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Espelho Ponto
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
               Justificativas
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Solicitar Abonos
            </a>
          </li>
        </ul>
      </div>
    </nav>
  

  </div>
</div>
</html>