config/routes.rb
Rails.application.routes.draw do
 
  #Rota Money Finalizadas 
  get 'moneys_exe/index'
  post 'moneys_exe/index'
  get '/export' => 'moneys_exe#export'
  
  #Historico de Justificativas
  
  get 'points_exe/index'
  post 'points_exe/index'
  

  #ROTA HISTORICO SALARIAL 
  get 'hist_moneys/index'
  post 'hist_moneys/index'

  #ROTA PONTO
  get 'points/index'
  post 'points/index'
  post 'points/justificar' => 'points#justificar'
  #post 'points/enviarTwo' => 'points#enviarTwo'
  get  'points/salvarDados'

  #Rota Money
  get 'moneys/index'
  post 'moneys/index'
  get '/money_export' => 'moneys#export'
  
  #exportando_pfd
  #get 'moneys/export'
   
  #Rota Dados Funcionários
  get 'dice/index'

  #Rota Página Principal
  get 'pages/index'
  delete 'pages/destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #Rotas login
  get 'login/index'
  root 'login#index'

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index 
    
    if params[:commit].to_s == "Acessar"
      puts "chamar autenticacao"
      if authenticationRM(params[:username].to_s,params[:password]) == "1"
        # puts "Tudo certo chamar login"
        # @username = login("USUARIO"+params[:username].to_s)
        # puts @username

        session[:username] = params[:username]
        session[:password] = params[:password]

        redirect_to pages_index_path
      else
        flash[:alert] = "Usuário ou Senha Invalida."
      end
    end
  

end


def authenticationRM(username,password) 
  
  @client = Savon.client(
    :wsdl => 'http://10.1.11.161/TOTVSBusinessConnect/wsDataServer.asmx?wsdl',
    # env_namespace: :soapenv,
    # element_form_default: :qualified,
    :log => true,
    :pretty_print_xml => true,
    basic_auth:["4456","040113"],
    ssl_verify_mode: :none,
    log_level: :debug, 
  )

  message = {
    "Usuario" => username.to_s,
    "Senha" => password,
  }  

  response = @client.call(
    :autentica_acesso_auth,
    message: message,
  )

  result = response.body[:autentica_acesso_auth_response][:autentica_acesso_auth_result]

  rescue Exception => e
    e.message

end

# def login(username) 

#   message = {
  
#       'DataServerName' => 'FOPFUNCDATA' ,
#       'Filtro' => "(PFUNC.CODPESSOA='"+session[:username]+"')",
#       'Contexto' => 'CODCOLIGADA=1;CODPESSOA=4425',
#       'Usuario' => '4456',
#       'Senha' => '040113',
#   }
  
#   response = @client.call(
#           :read_view_auth,
#           message: message,
#           )
          
#   result = response.body[:read_view_auth_response][:read_view_auth_result]
  
#   @doc = Nokogiri::Slop(result)

#   result = @doc.NewDataSet.PFunc.CODPESSOA.content

# end


end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title> Portal Pintos </title>


    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body class="text-center">
    <form class="form-signin">
    <%= form_tag login_index_path do %>
     
  <img class="mb-4" src="https://www.oster.com.br/arquivos/_OSTERBRASIL_campanha-natal-2017-pintos.png" alt="" width="250" height="100">
  <h1 class="h3 mb-3 font-weight-normal">Novo Portal Pintos</h1>
  <label for="inputText" class="sr-only">Usuário</label>
   <%= text_field_tag :username , "", class: 'form-control',placeholder: "Usuário"%>
  <label for="inputPassword" class="sr-only">Senha</label>
   <%= text_field_tag :password , "", class: 'form-control',placeholder: "Senha", type: 'password'%>
  <div class="checkbox mb-3">
  <% if flash[:alert].present? %>
   <div class="alert alert-danger alert-dismissible fade show" role="alert">
               <strong><%= flash[:alert]%> </strong> 
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
  </button>
    <% end %>
    
  </div>
    <label>
      <input type="checkbox" value="remember-me"> Ajuda
    </label>
  </div>
  <%= submit_tag "Acessar" , class: 'btn btn-lg btn-primary btn-block'%>
  <p class="mt-5 mb-3 text-muted">&copy; 2019-2020</p>
   <%# end %>
  <% end %>
</form>
</body>
</html>